# Generated by Django 5.0 on 2023-12-30 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_home_user_add'),
        ('restaurant', '0002_alter_restaurant_delivery'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('finish_cancel', models.CharField(choices=[('F', 'finish'), ('C', 'cancel')], max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('distance', models.IntegerField()),
                ('Estimated_arrival', models.IntegerField()),
                ('promo_code', models.CharField(max_length=30)),
                ('add_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
