# Generated by Django 5.0 on 2023-12-30 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Estimated_arrival',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='dish_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.dish')),
            ],
        ),
    ]
