# Generated by Django 5.0 on 2024-01-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_estimated_arrival_alter_cart_distance_and_more'),
        ('user', '0003_user_custom_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_custom'),
        ),
    ]
