# Generated by Django 5.0 on 2024-01-06 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_remove_work_user_add_add_id_and_more'),
        ('cart', '0004_remove_cart_user_id_cart_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='add_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.user_add'),
        ),
    ]
