# Generated by Django 5.0 on 2024-01-09 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_add_id'),
        ('dish', '0002_dish_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Food_is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='On_the_way',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='dishes',
            field=models.ManyToManyField(related_name='list_of_cart_dish', to='dish.dish'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Estimated_arrival',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='finish_cancel',
            field=models.CharField(choices=[('F', 'finish'), ('C', 'cancel'), ('N', 'Not_started'), ('D', 'doing')], default='N', max_length=1),
        ),
        migrations.DeleteModel(
            name='dish_cart',
        ),
    ]
