# Generated by Django 5.0 on 2024-01-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_food_is_ready_cart_on_the_way_cart_dishes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='rest_name',
            field=models.CharField(default='', max_length=68),
        ),
    ]
