# Generated by Django 5.0 on 2024-01-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_rest_name'),
        ('dish', '0002_dish_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='dishes',
        ),
        migrations.CreateModel(
            name='cart_dish_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('cart_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='cart.cart')),
                ('dish_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='dish.dish')),
            ],
        ),
    ]
