# Generated by Django 5.0 on 2024-01-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_delete_address_delete_home_user_add_and_more'),
        ('cart', '0008_remove_cart_dishes_cart_dish_table'),
        ('restaurant', '0005_alter_restaurant_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='add_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_cart', to='address.user_add'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_cart', to='restaurant.restaurant'),
        ),
    ]
