# Generated by Django 5.0 on 2024-01-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cart_add_id_alter_cart_rest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_dish_table',
            name='cart_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='dish_cart', to='cart.cart'),
        ),
    ]
