# Generated by Django 5.0 on 2024-01-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cart_estimated_arrival_alter_cart_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='finish_cancel',
            field=models.CharField(choices=[('F', 'finish'), ('C', 'cancel'), ('N', 'Not_started'), ('D', 'doing'), ('M', 'manager')], default='N', max_length=1),
        ),
    ]
