# Generated by Django 5.0 on 2024-01-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_image_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_rest',
            name='rest_id',
        ),
        migrations.RemoveField(
            model_name='like_rest',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='like_dish',
        ),
        migrations.DeleteModel(
            name='like_rest',
        ),
    ]
