# Generated by Django 5.0 on 2023-12-30 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0002_alter_restaurant_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/dish/')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300, null=True)),
                ('fee', models.CharField(default='free', max_length=20)),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
