# Generated by Django 5.0 on 2024-01-09 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='favourite_dish', to=settings.AUTH_USER_MODEL),
        ),
    ]
