# Generated by Django 5.0 on 2023-12-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
