# Generated by Django 5.0 on 2024-01-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_rest_user_add_work_user_add'),
        ('user', '0003_user_custom_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_user_add',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_custom'),
        ),
        migrations.AlterField(
            model_name='work_user_add',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_custom'),
        ),
    ]
