# Generated by Django 5.0 on 2024-01-06 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_remove_home_user_add_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_user_add',
            name='add_id',
        ),
        migrations.RemoveField(
            model_name='rest_user_add',
            name='add_id',
        ),
        migrations.RemoveField(
            model_name='home_user_add',
            name='add_id',
        ),
        migrations.RemoveField(
            model_name='home_user_add',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='rest_user_add',
            name='rest_id',
        ),
        migrations.RemoveField(
            model_name='work_user_add',
            name='owner',
        ),
        migrations.CreateModel(
            name='user_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=20)),
                ('is_work', models.BooleanField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
