# Generated by Django 5.0 on 2024-01-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_remove_work_user_add_add_id_and_more'),
        ('cart', '0005_alter_cart_add_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='address',
        ),
        migrations.DeleteModel(
            name='Home_user_add',
        ),
        migrations.DeleteModel(
            name='Rest_user_add',
        ),
        migrations.DeleteModel(
            name='Work_user_add',
        ),
    ]
