# Generated by Django 5.0 on 2023-12-30 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'Burger'), ('F', 'Fish'), ('C', 'Chicken'), ('A', 'Asian'), ('P', 'Pizza')], max_length=25)),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('range_dist', models.IntegerField()),
                ('offer', models.CharField(max_length=25)),
                ('opening_time', models.IntegerField()),
                ('delivery', models.FloatField()),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/restaurant/')),
            ],
        ),
    ]
