# Generated by Django 5.0 on 2024-01-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery',
            field=models.FloatField(default=0),
        ),
    ]
